### ISSUE TITLE
Wrong statement in JPA Mapping part about length/precision etc.

### ISSUE THREAD

**Issue by beikov** [datanucleus/docs-accessplatform#6]
In `_mapping_schema.adoc` you write 

> JPA does allow permit control over the length/precision/scale of columns. So we define this as follows

which is wrong. One can use the `@Column` annotation to define the length/precision etc. You can actually also define the DBMS type with `columnDefinition` but that doesn't affect the way the column value is accessed via JDBC nor does it play well with separating the length/precision.

I guess that JDBC type changes the way values are accessed/written via the JDBC API? This should be clarified and the statement about JPA not permitting control over DBMS specific types should be corrected.

**Comment by andyjefferson** [comment]
Fixed in GitHub, thx. Hopefully the wording is clearer now; otherwise a pull request could be provided ;-)

**Comment by beikov** [comment]
Yep looks better now, thanks 👍
